spring:
    h2.console:
        enable: true
        path: /h2-console
        settings:
            trace: false
            web-allow-others: false
    datasource:
        password: sa
        username: sa
        url: jdbc:h2:mem:test;MODE=PostgreSQL;
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 0
